const usd = n => n == null ? '—' : new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
export default function ExecutorShadow({study}) {
  const portfolios = study?.portfolios?.length ? study.portfolios : ['Baseline · 8% stop','Signal reset + 4h · 8% stop','Signal reset + 4h · volatility stop'].map((label,i)=>({id:i,label,waitingForStart:true,closed:'—',open:'—'}));
  return <section className="executor-performance executor-shadow">
    <div className="executor-performance-heading"><div><span className="executor-eyebrow">Forward experiment · virtual orders only</span><h2>Re-entry and stop placement</h2><p>{study?.started_at ? `Started ${new Date(study.started_at*1000).toLocaleString()} · ${usd(study.capital)} per portfolio` : 'Waiting for the updated backend and the first eligible scan. No historical results are imported.'}</p></div></div>
    {study?.error && <p className="executor-data-note">{study.error}</p>}
    {<div style={{overflowX:'auto'}}><table className="executor-shadow-table"><thead><tr><th>Rules</th><th>Closed / open</th><th>Realized</th><th>Unrealized</th><th>Combined</th><th>After estimated costs</th><th>Observed drawdown</th></tr></thead><tbody>{portfolios.map(p=><tr key={p.id}><td>{p.label}{!p.fresh && !p.waitingForStart && <small style={{display:'block'}}>Awaiting fresh marks</small>}</td><td>{p.closed} / {p.open}</td><td>{usd(p.realized)}</td><td>{usd(p.unrealized)}</td><td>{usd(p.combined)}</td><td>{usd(p.net_estimate)}</td><td>{p.max_drawdown_pct == null ? '—' : `${p.max_drawdown_pct.toFixed(2)}%`}</td></tr>)}</tbody></table></div>}
    <details className="executor-method"><summary>Experiment rules and stop calculations</summary><p>All portfolios start empty on the same scan and receive the same observed prices, eligible markets and signal sizing. This long-only study does not send orders. The baseline keeps the current 8% stop. The second portfolio also requires a signal reset and four hours after its own last exit.</p><p>The third uses that same re-entry rule with a fixed entry stop two times the average true range of the last 14 completed four-hour candles, bounded between 4% and 12%. Wider stops reduce position size to keep planned dollar risk at or below the baseline. Tighter stops do not increase size. Missing volatility data blocks entry in this variant.</p><p>Every variant retains the existing break-even rule: arm after a 5% observed gain, then exit at or below entry. Stops are evaluated at scan prices, so gaps can exceed planned risk. Stop distance is fixed at entry, not widened during a trade.</p><p>Estimated costs are 0.05% of notional on each executed virtual side. Open positions have no exit-cost reserve; funding and market impact are excluded. Drawdown is measured at fresh scan marks after estimated costs, not intrabar. Marks older than six hours withhold combined results. These new observations are separate from the six-month performance history.</p></details>
    {study?.portfolios?.length>0 && <details className="executor-method"><summary>Inspect open shadow stops</summary>{study.portfolios.map(p=><div key={p.id}><h3>{p.label}</h3>{Object.entries(p.positions).length ? Object.entries(p.positions).map(([symbol,pos])=><p key={symbol}>{symbol} · stop {new Intl.NumberFormat('en-US',{maximumSignificantDigits:7}).format(pos.stop_price)} · {(pos.stop_fraction*100).toFixed(2)}% from entry · allocation {usd(pos.cost)} · planned risk {usd(pos.planned_risk_usd)}</p>) : <p>No open shadow positions.</p>}</div>)}</details>}
  </section>;
}
