'use client';
import { useState,useMemo,useEffect } from 'react';
import { flushSync } from 'react-dom';
import Link from 'next/link';
import { ArrowRight,ArrowUpRight,ArrowDownRight,Search,Star,ScanLine,BookOpen,LockKeyhole,SlidersHorizontal,ChevronRight,ArrowLeft,Info,Check,Activity } from 'lucide-react';
import { Brand,TrendChart } from '@/components/reflex-brand';
import { Tabs,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { Sheet,SheetContent,SheetTitle,SheetDescription } from '@/components/ui/sheet';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Table,TableHeader,TableHead,TableBody,TableRow,TableCell } from '@/components/ui/table';
import { SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar } from '@/components/ui/sidebar';
import { assets,forTimeframe,filterAssets,price,tone,type Asset } from '@/lib/scanner-data';
const regimes=['All regimes','Markup','Accumulation','Distribution','Blowoff','Markdown','Capitulation'];
function Spark({asset,tf}:{asset:Asset;tf:string}){const points=Array.from({length:22},(_,i)=>{const wave=Math.sin(i*1.7+asset.symbol.charCodeAt(0))*7+Math.cos(i*.7)*3;const rise=asset.change>0?35-i*1.1:9+i*1.1;return `${i*4},${rise+wave+(tf==='4H'?Math.sin(i)*3:0)}`}).join(' ');return <svg viewBox="0 0 84 48" className="spark" aria-label={`${asset.symbol} illustrative ${tf} trend`} role="img"><polyline points={points} fill="none" stroke={asset.change>0?'#85ddac':'#f38f9d'} strokeWidth="1.5"/></svg>}
function AppNav({watch,setWatch,count}:{watch:boolean;setWatch:(v:boolean)=>void;count:number}){const{setOpenMobile}=useSidebar();return <Sidebar className="scanner-sidebar"><SidebarHeader className="scanner-logo"><Brand/></SidebarHeader><SidebarContent><div className="nav-caption mono">WORKSPACE</div><SidebarMenu className="scanner-nav"><SidebarMenuItem><SidebarMenuButton isActive={!watch} onClick={()=>{setWatch(false);setOpenMobile(false)}}><ScanLine/><span>Market scanner</span></SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton isActive={watch} onClick={()=>{setWatch(true);setOpenMobile(false)}}><Star/><span>Watchlist</span><span className="nav-count mono">{count}</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu><div className="nav-caption mono">EXPLORE REFLEX</div><SidebarMenu className="scanner-nav"><SidebarMenuItem><SidebarMenuButton render={<Link href="/#methodology"/>}><BookOpen/><span>The cycle engine</span></SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton render={<Link href="/access"/>}><LockKeyhole/><span>Token access</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu><div className="sidebar-note"><span className="pill">Design preview</span><p>A working glimpse of the Reflex experience, with illustrative market data.</p></div></SidebarContent><SidebarFooter className="scanner-sidebar-footer"><div className="sidebar-access"><LockKeyhole size={19}/><strong>Hold. Verify. Access.</strong><p>Discover the proposed token holding requirement.</p><Link href="/access">Explore access <ArrowRight size={14}/></Link></div><Link href="/" className="back-link"><ArrowLeft size={15}/> Back to Reflex</Link></SidebarFooter></Sidebar>}
export default function Scanner(){const[tf,setTf]=useState('1D');const[query,setQuery]=useState('');const[regime,setRegime]=useState('All regimes');const[sort,setSort]=useState('priority');const[watch,setWatch]=useState(false);const[favorites,setFavorites]=useState(['BTC','SOL','HYPE']);const[selected,setSelected]=useState<Asset|null>(null);const[hydrated,setHydrated]=useState(false);
useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('reflex-preview-watchlist')||'null');if(Array.isArray(saved))setFavorites(saved.filter(x=>typeof x==='string'&&assets.some(a=>a.symbol===x)))}catch{}setHydrated(true)},[]);
useEffect(()=>{if(hydrated)try{localStorage.setItem('reflex-preview-watchlist',JSON.stringify(favorites))}catch{}},[favorites,hydrated]);
const toggle=(symbol:string)=>setFavorites(prev=>prev.includes(symbol)?prev.filter(s=>s!==symbol):[...prev,symbol]);
const rows=useMemo(()=>forTimeframe(tf),[tf]);const filtered=useMemo(()=>filterAssets(rows,query,regime,watch?favorites:null,sort),[rows,query,regime,watch,favorites,sort]);const markup=rows.filter(a=>a.regime==='Markup').length;const buys=rows.filter(a=>a.signal==='Buy').length;
useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,opts:unknown)=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:'filter_reflex_scanner',title:'Filter Reflex demo scanner',description:'Set the visible demo scanner timeframe, asset search and regime. Returns matching illustrative assets. Does not access live market data.',inputSchema:{type:'object',properties:{query:{type:'string'},timeframe:{enum:['4H','1D']},regime:{enum:regimes}},required:['query','timeframe','regime'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const v=input as {query:string;timeframe:string;regime:string};if(!v||typeof v.query!=='string'||!['4H','1D'].includes(v.timeframe)||!regimes.includes(v.regime))throw new Error('Provide a query, valid timeframe and regime.');flushSync(()=>{setQuery(v.query);setTf(v.timeframe);setRegime(v.regime);setWatch(false);setSort('priority')});return {data:'illustrative',assets:filterAssets(forTimeframe(v.timeframe),v.query,v.regime,null,'priority').map(a=>({symbol:a.symbol,regime:a.regime,priority:a.priority}))}}},{signal:controller.signal})).catch(()=>{})}catch{}return()=>controller.abort()},[]);
return <SidebarProvider style={{'--sidebar-width':'225px'} as React.CSSProperties}><a className="skip" href="#scanner-main">Skip to scanner</a><AppNav watch={watch} setWatch={setWatch} count={favorites.length}/><div className="scanner-body"><header className="app-topbar"><div><SidebarTrigger/><span className="app-breadcrumb">Workspace <ChevronRight size={14}/> <strong>{watch?'Watchlist':'Market scanner'}</strong></span></div><div><span className="demo-label"><span className="dot"/> Sample data</span><Link href="/access" className="btn small secondary"><LockKeyhole size={14}/> Token access</Link></div></header><main className="scanner-main" id="scanner-main"><div className="scanner-title"><div><div className="eyebrow">The market, in perspective</div><h1>{watch?'Your watchlist.':'Market scanner.'}</h1><p>{watch?'A closer eye on the assets you follow.':'Find the setup. Understand the context.'}</p></div><div className="snapshot"><span className="mono">ILLUSTRATIVE SNAPSHOT</span><span>Explore freely · No wallet connected</span></div></div>
<div className="market-summary"><article><span>Market regime <Activity size={14}/></span><strong className="positive">Constructive <ArrowUpRight size={21}/></strong><small>{markup} of {rows.length} sample assets in markup</small></article><article><span>Assets scanned <ScanLine size={14}/></span><strong className="mono">{rows.length}<em> / sample universe</em></strong><small>Cross-asset cycle intelligence</small></article><article><span>Buy signals <ArrowUpRight size={14}/></span><strong className="mono positive">{buys}<em> across {tf} samples</em></strong><small>Inspect the evidence behind each</small></article><article><span>Timeframe <LayersIcon/></span><strong className="mono">{tf}<em> {tf==='1D'?'Daily cycle':'Four-hour cycle'}</em></strong><small>Compare context across timeframes</small></article></div>
<div className="scanner-middle"><div className="breadth-panel"><div className="panel-label"><span>Cycle distribution</span><span className="mono">{rows.length} ASSETS</span></div><div className="breadth-bar" aria-label="Regime distribution">{regimes.slice(1).map((r,i)=>{const count=rows.filter(a=>a.regime===r).length;return count>0?<div key={r} style={{flex:count,background:['#85ddac','#72e6e5','#cbaa75','#d4a66e','#f38f9d','#ae778a'][i]}} title={`${r}: ${count}`}/>:null})}</div><div className="breadth-legend">{regimes.slice(1).map((r,i)=><button key={r} onClick={()=>setRegime(r)} aria-pressed={regime===r}><i style={{background:['#85ddac','#72e6e5','#cbaa75','#d4a66e','#f38f9d','#ae778a'][i]}}/>{r}<b>{rows.filter(a=>a.regime===r).length}</b></button>)}</div></div><div className="context-panel"><span className="eyebrow"><Info size={14}/> Perspective</span><p>Strength is concentrated in markup assets. Compare the daily cycle with 4H before forming a view.</p><a href="/#methodology">How to read regimes <ArrowUpRight size={14}/></a></div></div>
<section className="scan-table-section" aria-label="Asset scanner"><div className="scan-controls"><div className="scanner-tab-name">{watch?'Watchlist':'All assets'} <span className="mono">{filtered.length}</span></div><Tabs value={tf} onValueChange={v=>setTf(String(v))} className="timeframe-tabs"><TabsList aria-label="Scanner timeframe"><TabsTrigger value="4H">4H</TabsTrigger><TabsTrigger value="1D">1D</TabsTrigger></TabsList></Tabs></div><div className="filter-bar"><label className="search-field"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search assets…" aria-label="Search assets"/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search">×</button>}</label><div className="filter-right"><Select value={regime} onValueChange={v=>setRegime(v||'All regimes')}><SelectTrigger className="filter-select" aria-label="Filter by regime"><SlidersHorizontal size={14}/><SelectValue/></SelectTrigger><SelectContent>{regimes.map(r=><SelectItem key={r} value={r}>{r}</SelectItem>)}</SelectContent></Select><Select value={sort} onValueChange={v=>setSort(v||'priority')} items={[{value:'priority',label:'Priority: high to low'},{value:'change',label:'24h change: high to low'},{value:'symbol',label:'Asset: A–Z'}]}><SelectTrigger className="filter-select" aria-label="Sort assets"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="priority">Priority: high to low</SelectItem><SelectItem value="change">24h change: high to low</SelectItem><SelectItem value="symbol">Asset: A–Z</SelectItem></SelectContent></Select></div></div>
<Table className="asset-table"><TableHeader><TableRow><TableHead><span className="sr-only">Watchlist</span></TableHead><TableHead>Asset</TableHead><TableHead>Price / 24h</TableHead><TableHead>Regime</TableHead><TableHead>Signal</TableHead><TableHead>Priority <span title="Illustrative ranking, not a probability of profit">ⓘ</span></TableHead><TableHead>Trend</TableHead><TableHead>Alignment</TableHead><TableHead><span className="sr-only">View details</span></TableHead></TableRow></TableHeader><TableBody>{filtered.map(a=><TableRow key={a.symbol}><TableCell><button className={`star-btn ${favorites.includes(a.symbol)?'saved':''}`} onClick={()=>toggle(a.symbol)} aria-label={`${favorites.includes(a.symbol)?'Remove':'Add'} ${a.symbol} ${favorites.includes(a.symbol)?'from':'to'} watchlist`} aria-pressed={favorites.includes(a.symbol)}><Star size={15} fill={favorites.includes(a.symbol)?'currentColor':'none'}/></button></TableCell><TableCell><button className="asset-name" onClick={()=>setSelected(a)}><span className="coin-avatar" style={{background:a.color+'18',color:a.color}}>{a.symbol==='BTC'?'₿':a.symbol==='ETH'?'Ξ':a.symbol.slice(0,1)}</span><span><strong>{a.symbol}</strong><small>{a.name}</small></span></button></TableCell><TableCell><span className="mono table-price">{price(a.price)}</span><small className={`table-change mono ${a.change>=0?'positive':'negative'}`}>{a.change>0?'+':''}{a.change.toFixed(2)}%</small></TableCell><TableCell><span className={`pill ${tone(a.regime)}`}>{a.regime}</span></TableCell><TableCell><span className={`signal-text ${a.signal==='Buy'?'positive':a.signal==='Sell'?'negative':'muted'}`}>{a.signal==='Buy'?<ArrowUpRight size={14}/>:a.signal==='Sell'?<ArrowDownRight size={14}/>:<span className="signal-dot"/>}{a.signal}</span></TableCell><TableCell><span className="priority-cell"><span className="mono">{a.priority}</span><span className="priority-meter"><i style={{width:`${a.priority}%`}}/></span></span></TableCell><TableCell><Spark asset={a} tf={tf}/></TableCell><TableCell><span className={a.confluence==='Aligned'?'aligned':'muted'}>{a.confluence==='Aligned'&&<Check size={13}/>} {a.confluence}</span></TableCell><TableCell><button className="detail-btn" onClick={()=>setSelected(a)} aria-label={`View ${a.symbol} setup`}><ChevronRight size={17}/></button></TableCell></TableRow>)}</TableBody></Table>
{filtered.length===0&&<div className="scan-empty"><Search size={28}/><h3>No assets match this view.</h3><p>{watch&&favorites.length===0?'Star an asset in the scanner to start your watchlist.':'Try a different asset name or clear the regime filter.'}</p><button className="btn secondary" onClick={()=>{setQuery('');setRegime('All regimes');if(watch&&favorites.length===0)setWatch(false)}}>Reset filters</button></div>}
<div className="table-footer"><span aria-live="polite">Showing {filtered.length} of {rows.length} sample assets</span><span>Priority is a ranking, not a win probability.</span></div></section><div className="scanner-bottom"><span><span className="dot"/> Preview mode · All prices and signals are illustrative</span><Link href="/">Reflex / Market intelligence <ArrowUpRight size={13}/></Link></div></main></div>
<Sheet open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null)}}><SheetContent className="asset-sheet">{selected&&<><div className="eyebrow">Setup detail · {tf} sample</div><SheetTitle className="detail-title">{selected.name} <span className="muted">/ {selected.symbol}</span></SheetTitle><SheetDescription>Illustrative market context. Not a live trade recommendation.</SheetDescription><div className="detail-price"><span className="mono">{price(selected.price)}</span><span className={selected.change>0?'positive':'negative'}>{selected.change>0?'+':''}{selected.change}%</span></div><TrendChart id="detail-chart" down={selected.change<0}/><div className="detail-badges"><span className={`pill ${tone(selected.regime)}`}>{selected.regime}</span><span className="pill">{selected.signal}</span></div><div className="detail-section"><h3>The setup</h3><p>{selected.note}</p></div><div className="detail-metrics"><div><span>Z-score</span><strong className="mono">{selected.z.toFixed(2)}</strong></div><div><span>Energy ratio</span><strong className="mono">{selected.energy.toFixed(2)}</strong></div><div><span>Priority</span><strong className="mono">{selected.priority}/100</strong></div><div><span>4H / 1D</span><strong>{selected.confluence}</strong></div></div><div className="detail-section"><h3>What would change the view?</h3><p>A regime transition, a reversal in trend energy, or disagreement between timeframes. Reassess the evidence when those conditions change.</p></div><button className="btn secondary" onClick={()=>toggle(selected.symbol)}><Star size={16} fill={favorites.includes(selected.symbol)?'currentColor':'none'}/>{favorites.includes(selected.symbol)?'Remove from watchlist':'Add to watchlist'}</button><p className="detail-disclaimer">The chart is conceptual and is not historical price data. Demo metrics are supplied examples.</p></>}</SheetContent></Sheet>
</SidebarProvider>}
function LayersIcon(){return <SlidersHorizontal size={14}/>}
