export type Asset={symbol:string;name:string;price:number;change:number;regime:string;signal:string;priority:number;z:number;energy:number;confluence:string;color:string;note:string};
export const assets:Asset[]=[
{symbol:'SOL',name:'Solana',price:184.32,change:5.21,regime:'Markup',signal:'Buy',priority:92,z:1.42,energy:1.36,confluence:'Aligned',color:'#b59afe',note:'Positive trend energy and a markup regime align across both timeframes. Check that momentum persists before drawing a conclusion.'},
{symbol:'BTC',name:'Bitcoin',price:96842.50,change:2.84,regime:'Markup',signal:'Buy',priority:89,z:1.18,energy:1.21,confluence:'Aligned',color:'#e8b46a',note:'The daily cycle and shorter-term trend are aligned. A loss of positive energy would weaken this illustrative setup.'},
{symbol:'ETH',name:'Ethereum',price:3248.76,change:3.12,regime:'Markup',signal:'Buy',priority:86,z:.96,energy:1.18,confluence:'Aligned',color:'#9faaf1',note:'Price is above its statistical baseline with positive trend energy. Watch for continuation rather than assuming the move will persist.'},
{symbol:'HYPE',name:'Hyperliquid',price:27.48,change:1.67,regime:'Accumulation',signal:'Watch',priority:78,z:.24,energy:1.03,confluence:'Mixed',color:'#85d9c5',note:'Price is near its baseline and the broader regime remains neutral. A confirmed transition would add evidence; it is not present in this example.'},
{symbol:'LINK',name:'Chainlink',price:21.86,change:4.06,regime:'Markup',signal:'Buy',priority:81,z:1.06,energy:1.16,confluence:'Aligned',color:'#86aaff',note:'Price deviation and energy suggest a constructive regime. Evaluate both timeframes and liquidity before interpreting the signal.'},
{symbol:'AVAX',name:'Avalanche',price:35.72,change:-.84,regime:'Accumulation',signal:'Watch',priority:62,z:.12,energy:1.01,confluence:'Mixed',color:'#f29898',note:'A neutral cycle with little directional energy. Watch for a regime change instead of treating a small price move as confirmation.'},
{symbol:'SUI',name:'Sui',price:3.84,change:7.32,regime:'Blowoff',signal:'Heavy trim',priority:74,z:3.62,energy:1.48,confluence:'Mixed',color:'#7ccbea',note:'Price is extremely extended relative to its baseline. Strong recent performance can coexist with elevated reversal risk.'},
{symbol:'ARB',name:'Arbitrum',price:.724,change:-2.36,regime:'Markdown',signal:'Sell',priority:58,z:-.68,energy:.86,confluence:'Aligned',color:'#92b7dc',note:'Negative trend energy supports the markdown regime. A recovery in both energy and structure would challenge this reading.'},
{symbol:'DOGE',name:'Dogecoin',price:.2845,change:-1.12,regime:'Distribution',signal:'Trim',priority:65,z:2.27,energy:.97,confluence:'Mixed',color:'#d7c383',note:'Price remains extended while trend energy fades. This combination suggests distribution in the illustrative cycle model.'},
{symbol:'OP',name:'Optimism',price:1.28,change:-4.18,regime:'Capitulation',signal:'Watch',priority:47,z:-1.34,energy:.72,confluence:'Mixed',color:'#ef8693',note:'Price is depressed with strongly negative energy. Capitulation alone does not establish a reversal or a safe entry.'},
];
export function forTimeframe(tf:string):Asset[]{return assets.map((a,i)=>tf==='1D'?a:{...a,priority:Math.max(30,a.priority-((i*3+5)%14)),z:Number((a.z*.81).toFixed(2)),energy:Number((a.energy*.97).toFixed(2)),regime:a.symbol==='HYPE'?'Markup':a.symbol==='LINK'?'Accumulation':a.regime,signal:a.symbol==='HYPE'?'Buy':a.symbol==='LINK'?'Watch':a.signal});}
export function tone(regime:string){return regime==='Markup'?'green':['Blowoff','Distribution'].includes(regime)?'amber':['Markdown','Capitulation'].includes(regime)?'red':''}
export function price(value:number){return value.toLocaleString('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:value<1?4:2})}
export function filterAssets(rows:Asset[],query:string,regime:string,favorites:string[]|null,sort:string){return rows.filter(a=>(a.symbol+' '+a.name).toLowerCase().includes(query.toLowerCase())&&(regime==='All regimes'||a.regime===regime)&&(!favorites||favorites.includes(a.symbol))).sort((a,b)=>sort==='change'?b.change-a.change:sort==='symbol'?a.symbol.localeCompare(b.symbol):b.priority-a.priority)}
